<?php
/**
 * @file
 * Main module file for DFP Lazyload.
 */

/**
 * Implements hook_menu().
 */
function dfp_lazyload_menu() {
  $items = array();
  $items['admin/structure/dfp_ads/lazyload'] = array(
    'title' => 'DFP Lazyload',
    'description' => 'Configure DFP Lazyload.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dfp_lazyload_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 15,
  );

  return $items;
}

/**
 * Implements hook_form().
 */
function dfp_lazyload_settings_form() {
  $form = array();

  // @TODO: Allow more than one slot configuration.
  $form['dfp_lazyload_machinename'] = array(
    '#type' => 'textfield',
    '#title' => t('Ad Slot'),
    '#maxlength' => 255,
    '#default_value' => variable_get('dfp_lazyload_machinename'),
    '#description' => t('Specify which ad slot to load.'),
    '#required' => TRUE,
  );

  $form['dfp_lazyload_frequency'] = array(
    '#type' => 'textfield',
    '#title' => t('Frequency'),
    '#maxlength' => 255,
    '#default_value' => variable_get('dfp_lazyload_frequency', 3),
    '#description' => t('Load a new ad slot every N items.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

